server:
  http:
    addr: 0.0.0.0:58080
    timeout: 30s
  grpc:
    addr: 0.0.0.0:9000
    timeout: 30s

data:
  database:
    driver: postgres
    source: postgres://erp_test_user:erp_test_pass@localhost:5432/erp_test_db?sslmode=disable
  redis:
    addr: localhost:6379
    read_timeout: 0.2s
    write_timeout: 0.2s

cache:
  redis:
    addr: localhost:6379
    password: ""
    db: 1
    pool_size: 10
    min_idle_conns: 5
    dial_timeout: 5s
    read_timeout: 3s
    write_timeout: 3s
    pool_timeout: 4s
    idle_timeout: 300s
  
  ttl:
    user_permissions: 600    # 10分钟
    user_roles: 600
    permission_rules: 1200   # 20分钟
    field_permissions: 1200
    doc_types: 1800         # 30分钟
    user_permission_level: 600

  key_prefix: "test_perm:"
  
  warmup:
    enabled: false
    on_startup: false
  
  cleanup:
    enabled: false
  
  monitoring:
    enabled: false
    
  performance:
    batch_size: 50
    max_concurrent_requests: 10
    circuit_breaker:
      enabled: false

auth:
  jwt_secret: test-jwt-secret-key-for-ci-testing
  token_expire: 7200s  # 2小时

log:
  level: debug
  format: json
  output: stdout

trace:
  endpoint: ""

environment: test